const HOST = 'http://192.168.1.3';
export default {
  URL_getcart: HOST + '/serverAppCk/getcart.php',
  URL_spmoinhat: HOST + '/serverAppCk/getspmoinhat.php',
  URL_gethh: HOST + '/serverAppCk/gettatcasanpham.php',
  URL_themhh: HOST + '/serverAppCk/themhanghoa.php',
  URL_xoahh: HOST + '/serverAppCk/xoahanghoa.php',
  URL_getch: HOST + '/serverAppCk/getcuahang.php',
  URL_gettk: HOST + '/serverAppCk/gettaikhoan.php',
  URL_xoatk: HOST + '/serverAppCk/xoataihoan.php',
  URL_themgh: HOST + '/serverAppCk/addcart.php',
  URL_suagh: HOST + '/serverAppCk/suagiohang.php',
  URL_xoagh: HOST + '/serverAppCk/xoagiohang.php',
  URL_gettk: HOST + '/serverAppCk/gettaikhoan.php',
  URL_getuser: HOST + '/serverAppCk/getuser.php',
  URL_getadmin: HOST + '/serverAppCk/getadmin.php',
  URL_sptheodm: HOST + '/serverAppCk/getsanpham.php',
  URL_gettintuc: HOST + '/serverAppCk/gettintuc.php',
  URL_themtk: HOST + '/serverAppCk/themtaikhoan.php',
  URL_themdh: HOST + '/serverAppCk/themdonhang.php',
};
